In [18]:
a = [10, 11, 12, 13, 14, 15]

In [19]:
import numpy as np

In [20]:
n_a = np.array(a) 

In [21]:
n_a

array([10, 11, 12, 13, 14, 15])

In [22]:
n_a[0]

10

In [23]:
n_a[1]

11

In [26]:
last_index = len(n_a) - 1

In [27]:
n_a[last_index]

15

In [28]:
ｎ_a[-1]

15

In [29]:
ｎ_a[-2]

14

In [32]:
n_a[0:3]

array([10, 11, 12])

In [33]:
n_a[:3]

array([10, 11, 12])

In [34]:
n_a[3:6]

array([13, 14, 15])

In [35]:
n_a[3:]

array([13, 14, 15])

In [36]:
n_a[2:4]

array([12, 13])

In [37]:
n_a[1::2] 

array([11, 13, 15])

In [38]:
n_b = np.array([100, 101, 102, 103, 104, 105])

In [40]:
n_c = np.concatenate([n_a, n_b])

In [41]:
np.sum(n_c)

690

In [42]:
np.max(n_c)

105

In [43]:
np.min(n_c)

10

In [44]:
np.average(n_c)

57.5

In [54]:
n_random = np.random.random(10)

In [49]:
n_random 

array([0.14365423, 0.99358905, 0.90027284, 0.24614619, 0.02860016,
       0.50446365, 0.59355054, 0.15096908, 0.40274666, 0.62984084])

In [55]:
np.max(n_random)

0.9308212967785259

In [56]:
np.min(n_random)

0.22031499877476113

In [57]:
np.sort(n_random)

array([0.220315  , 0.34547944, 0.39625986, 0.40099943, 0.45224149,
       0.48498313, 0.54835575, 0.74262219, 0.77328456, 0.9308213 ])

In [58]:
np.argsort(n_random)

array([7, 3, 4, 6, 0, 9, 8, 2, 1, 5], dtype=int64)

In [59]:
np.sort(n_random)[::-1]

array([0.9308213 , 0.77328456, 0.74262219, 0.54835575, 0.48498313,
       0.45224149, 0.40099943, 0.39625986, 0.34547944, 0.220315  ])